// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxCljXZa46HIbxeLqD3gJHeBfXhEf8L9k',
    appId: '1:381972788771:web:2f1e494ec749964f0be396',
    messagingSenderId: '381972788771',
    projectId: 'immunicare-a960d',
    authDomain: 'immunicare-a960d.firebaseapp.com',
    storageBucket: 'immunicare-a960d.firebasestorage.app',
    measurementId: 'G-LJDDR1MBVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSP1BjdShkWlYHoUWhwS9O35-I3r5did8',
    appId: '1:381972788771:android:92a76e1268ecc29a0be396',
    messagingSenderId: '381972788771',
    projectId: 'immunicare-a960d',
    storageBucket: 'immunicare-a960d.firebasestorage.app',
  );
}
